"""empty message

Revision ID: 42ce5f490a70
Revises: 
Create Date: 2024-07-03 17:58:14.269094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce5f490a70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('c_ID', sa.String(), nullable=False),
    sa.Column('c_name', sa.String(length=50), nullable=False),
    sa.Column('c_email', sa.String(length=255), nullable=False),
    sa.Column('c_contact', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('c_ID')
    )
    op.create_table('inventoryitem',
    sa.Column('item_SKU', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_desc', sa.String(length=255), nullable=True),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('item_qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_SKU'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('staff',
    sa.Column('s_ID', sa.String(), nullable=False),
    sa.Column('s_name', sa.String(length=50), nullable=False),
    sa.Column('s_email', sa.String(length=255), nullable=False),
    sa.Column('s_isAdmin', sa.Boolean(), nullable=False),
    sa.Column('s_contact', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('s_ID')
    )
    op.create_table('transaction',
    sa.Column('t_ID', sa.String(), nullable=False),
    sa.Column('c_ID', sa.String(), nullable=False),
    sa.Column('t_date', sa.DateTime(), nullable=False),
    sa.Column('t_amount', sa.Integer(), nullable=False),
    sa.Column('t_category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['c_ID'], ['customer.c_ID'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('t_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('inventoryitem')
    op.drop_table('customer')
    # ### end Alembic commands ###
