"""empty message

Revision ID: ba0298fcff70
Revises: 016538b52200
Create Date: 2024-07-13 00:50:29.578933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0298fcff70'
down_revision = '016538b52200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_id', sa.Integer(), nullable=False))
        batch_op.drop_column('c_ID')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('c_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('s_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('t_time', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('transaction_c_ID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['s_id'], ['s_id'], ondelete='NO ACTION')
        batch_op.create_foreign_key(None, 'customer', ['c_id'], ['c_id'], ondelete='NO ACTION')
        batch_op.drop_column('t_category')
        batch_op.drop_column('c_ID')
        batch_op.drop_column('t_ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_ID', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('c_ID', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('t_category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_c_ID_fkey', 'customer', ['c_ID'], ['c_ID'])
        batch_op.drop_column('t_time')
        batch_op.drop_column('s_id')
        batch_op.drop_column('c_id')
        batch_op.drop_column('t_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_ID', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('c_id')

    # ### end Alembic commands ###
